// Paths only: scene has no eager regional SpriteFrame dependencies.
export const BUBBLE_SCENE_SPRITES: readonly (readonly [string,string])[] = [
  [
    "Background",
    "visual/regions/cloud/backgrounds/background"
  ],
  [
    "Environment/IslandLeft",
    "visual/regions/cloud/backgrounds/island-left"
  ],
  [
    "Environment/IslandRight",
    "visual/regions/cloud/backgrounds/island-right"
  ],
  [
    "Foreground",
    "visual/regions/cloud/backgrounds/foreground-bottom"
  ],
  [
    "Playfield/Counter/DownArrow",
    "visual/regions/cloud/hud/hud-down-arrow"
  ],
  [
    "Playfield/Counter/Slot0",
    "visual/common/hud/hud-counter-slot-empty"
  ],
  [
    "Playfield/Counter/Bead0",
    "visual/common/hud/hud-counter-bead"
  ],
  [
    "Playfield/Counter/Slot1",
    "visual/common/hud/hud-counter-slot-empty"
  ],
  [
    "Playfield/Counter/Bead1",
    "visual/common/hud/hud-counter-bead"
  ],
  [
    "Playfield/Counter/Slot2",
    "visual/common/hud/hud-counter-slot-empty"
  ],
  [
    "Playfield/Board/Bubble-0-0",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-0-1",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-0-1/Frosting",
    "visual/regions/cloud/bubbles/frosting-overlay"
  ],
  [
    "Playfield/Board/Bubble-0-2",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-0-3",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-0-4",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-0-5",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-0-6",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-0-7",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-0-8",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-0-9",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-0-10",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-0-11",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-0-12",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-0-13",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-0-14",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-1-0",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-1-1",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-1-1/Frosting",
    "visual/regions/cloud/bubbles/frosting-overlay"
  ],
  [
    "Playfield/Board/Bubble-1-2",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-1-3",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-1-4",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-1-5",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-1-6",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-1-7",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-1-8",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-1-9",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-1-10",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-1-11",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-1-12",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-1-12/Frosting",
    "visual/regions/cloud/bubbles/frosting-overlay"
  ],
  [
    "Playfield/Board/Bubble-1-13",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-2-0",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-2-1",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-2-2",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-2-3",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-2-4",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-2-5",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-2-6",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-2-7",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-2-8",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-2-9",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-2-10",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-2-11",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-2-12",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-2-13",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-2-14",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-3-0",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-3-1",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-3-2",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-3-3",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-3-4",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-3-5",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-3-6",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-3-7",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-3-8",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-3-9",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-3-9/Frosting",
    "visual/regions/cloud/bubbles/frosting-overlay"
  ],
  [
    "Playfield/Board/Bubble-3-10",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-3-11",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-3-12",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Launcher/Pedestal",
    "visual/regions/cloud/launcher/launcher-pedestal"
  ],
  [
    "Playfield/Launcher/TurretPivot/CurrentBall",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Launcher/TurretPivot/TurretArtwork",
    "visual/regions/cloud/launcher/launcher-head"
  ],
  [
    "Playfield/Launcher/NextBall",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Launcher/Swap",
    "visual/regions/cloud/launcher/swap-icon"
  ],
  [
    "Playfield/Items/Item-bomb",
    "visual/common/items/item-button-base"
  ],
  [
    "Playfield/Items/Item-bomb/Icon",
    "visual/common/items/item-bomb"
  ],
  [
    "Playfield/Items/Item-bomb/Badge",
    "visual/common/items/item-count-badge"
  ],
  [
    "Playfield/Items/Item-wildcard",
    "visual/common/items/item-button-base"
  ],
  [
    "Playfield/Items/Item-wildcard/Icon",
    "visual/common/items/item-wildcard"
  ],
  [
    "Playfield/Items/Item-wildcard/Badge",
    "visual/common/items/item-count-badge"
  ],
  [
    "Playfield/Items/Item-clear-bottom",
    "visual/common/items/item-button-base"
  ],
  [
    "Playfield/Items/Item-clear-bottom/Icon",
    "visual/common/items/item-clear-bottom"
  ],
  [
    "Playfield/Items/Item-clear-bottom/Badge",
    "visual/common/items/item-count-badge"
  ],
  [
    "Pause",
    "visual/regions/cloud/hud/hud-pause-button"
  ],
  [
    "Playfield/Boss/Body",
    "visual/regions/cloud/boss/boss-pudding-body"
  ],
  [
    "Playfield/Boss/LeftFist",
    "visual/regions/cloud/boss/boss-pudding-fist-left"
  ],
  [
    "Playfield/Boss/RightFist",
    "visual/regions/cloud/boss/boss-pudding-fist-right"
  ],
  [
    "Playfield/Boss/Crown",
    "visual/regions/cloud/boss/boss-pudding-crown"
  ],
  [
    "Playfield/Boss/HealthTrack",
    "visual/common/hud/hud-boss-health-track"
  ],
  [
    "Playfield/Boss/HealthFill",
    "visual/common/hud/hud-boss-health-fill"
  ],
  [
    "Playfield/Counter/BossSkill",
    "visual/regions/cloud/hud/hud-frosting-skill"
  ],
  [
    "RewardAssets/panel",
    "visual/common/reward-common/reward-panel"
  ],
  [
    "RewardAssets/card",
    "visual/common/reward-common/reward-card"
  ],
  [
    "RewardAssets/button",
    "visual/common/reward-common/reward-button"
  ],
  [
    "RewardAssets/selection",
    "visual/common/reward-common/reward-selection"
  ],
  [
    "RewardAssets/check",
    "visual/common/reward-common/reward-check"
  ],
  [
    "RewardAssets/subtitle",
    "visual/common/reward-common/reward-subtitle"
  ],
  [
    "RewardAssets/cloud-title",
    "visual/regions/cloud/reward-cloud/reward-cloud-title"
  ],
  [
    "RewardAssets/attack-heart",
    "visual/regions/cloud/vfx/attack-energy-heart"
  ],
  [
    "RewardAssets/dialog-panel",
    "visual/common/dialog-common/dialog-panel"
  ],
  [
    "RewardAssets/dialog-primary",
    "visual/common/dialog-common/dialog-primary"
  ],
  [
    "RewardAssets/dialog-secondary",
    "visual/common/dialog-common/dialog-secondary"
  ],
  [
    "RewardAssets/shard-red-1",
    "visual/regions/cloud/vfx/attack-candy-shards/red-01"
  ],
  [
    "RewardAssets/shard-red-2",
    "visual/regions/cloud/vfx/attack-candy-shards/red-02"
  ],
  [
    "RewardAssets/shard-yellow-1",
    "visual/regions/cloud/vfx/attack-candy-shards/yellow-01"
  ],
  [
    "RewardAssets/shard-yellow-2",
    "visual/regions/cloud/vfx/attack-candy-shards/yellow-02"
  ],
  [
    "RewardAssets/shard-blue-1",
    "visual/regions/cloud/vfx/attack-candy-shards/blue-01"
  ],
  [
    "RewardAssets/shard-blue-2",
    "visual/regions/cloud/vfx/attack-candy-shards/blue-02"
  ],
  [
    "RewardAssets/shard-purple-1",
    "visual/regions/cloud/vfx/attack-candy-shards/purple-01"
  ],
  [
    "RewardAssets/shard-purple-2",
    "visual/regions/cloud/vfx/attack-candy-shards/purple-02"
  ],
  [
    "RewardAssets/frost-1",
    "visual/regions/cloud/vfx/frosting-debris/fragment-01"
  ],
  [
    "RewardAssets/frost-2",
    "visual/regions/cloud/vfx/frosting-debris/fragment-02"
  ],
  [
    "RewardAssets/frost-3",
    "visual/regions/cloud/vfx/frosting-debris/fragment-03"
  ],
  [
    "RewardAssets/frost-4",
    "visual/regions/cloud/vfx/frosting-debris/fragment-04"
  ],
  [
    "RewardAssets/frost-5",
    "visual/regions/cloud/vfx/frosting-debris/fragment-05"
  ],
  [
    "RewardAssets/frost-6",
    "visual/regions/cloud/vfx/frosting-debris/fragment-06"
  ],
  [
    "RewardAssets/frost-7",
    "visual/regions/cloud/vfx/frosting-debris/fragment-07"
  ],
  [
    "Playfield/Board/Bubble-3-13",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-4-0",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-4-1",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-4-2",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-4-3",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-4-4",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-4-5",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-4-6",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-4-7",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-4-8",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-4-9",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-4-10",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-4-11",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-4-12",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-4-13",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-4-14",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-5-0",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-5-1",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-5-2",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-5-3",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-5-4",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-5-5",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-5-6",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-5-7",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-5-8",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-5-9",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-5-10",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-5-11",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-5-12",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-5-13",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-6-0",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-6-1",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-6-2",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-6-3",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-6-4",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-6-5",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-6-6",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-6-7",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-6-8",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-6-9",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-6-10",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-6-11",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-6-12",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-6-13",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-6-14",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-7-0",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-7-1",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-7-2",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-7-3",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-7-4",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-7-5",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-7-6",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-7-7",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-7-8",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-7-9",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-7-10",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-7-11",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-7-12",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-7-13",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-8-0",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-8-1",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-8-2",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-8-3",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-8-4",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-8-5",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-8-6",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-8-7",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-8-8",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-8-9",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-8-10",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-8-11",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-8-12",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-8-13",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-8-14",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-9-0",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-9-1",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-9-2",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-9-3",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-9-4",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-9-5",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-9-6",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-9-7",
    "visual/regions/cloud/bubbles/bubble-purple"
  ],
  [
    "Playfield/Board/Bubble-9-8",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-9-9",
    "visual/regions/cloud/bubbles/bubble-red"
  ],
  [
    "Playfield/Board/Bubble-9-10",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-9-11",
    "visual/regions/cloud/bubbles/bubble-yellow"
  ],
  [
    "Playfield/Board/Bubble-9-12",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Board/Bubble-9-13",
    "visual/regions/cloud/bubbles/bubble-blue"
  ],
  [
    "Playfield/Launcher/FixedConnector",
    "visual/regions/cloud/launcher/launcher-connector"
  ],
  [
    "CloudTransition",
    "visual/regions/cloud/backgrounds/cloud-transition"
  ],
  [
    "RewardAssets/boss-alert",
    "visual/common/transition/boss-alert"
  ],
  [
    "RewardAssets/cloud-curtain",
    "visual/common/transition/cloud-curtain"
  ],
  [
    "Playfield/Items/Item-bomb/NamePlate",
    "visual/common/items/item-name-plate"
  ],
  [
    "Playfield/Items/Item-wildcard/NamePlate",
    "visual/common/items/item-name-plate"
  ],
  [
    "Playfield/Items/Item-clear-bottom/NamePlate",
    "visual/common/items/item-name-plate"
  ],
  [
    "Playfield/Counter/PendingRow",
    "visual/common/hud/hud-insert-row"
  ]
];
